### ISSUE TITLE
Transactional Enqueuing

### ISSUE THREAD

**Issue by ShahzadUmair** [googleapis/python-tasks#26]
**Is your feature request related to a problem? Please describe.**
We wish to migrate our app from python2 to python3 and we heavily rely on transactional enqueuing. The migration doc does not explain how this might work with cloud ndb and tasks. 

 **Describe the solution you'd like**
There should be some way of attaching actions with the transaction with or without limit of allowed actions. 

 **Describe alternatives you've considered**
We considered storing the tasks in datastore during the transaction and dequeue later to run when transaction is completed but that seems to consume an entity group (25 entity group limit) which is not feasible either in our case. 

 **Additional context**
N/A

**Comment by averikitsch** [comment]
Hi! Currently we do not support transactional tasks.  For Cloud Tasks feature requests, we recommend you file an issue in their public issue tracker.  You can find that https://issuetracker.google.com/savedsearches/5433985. As of right now, you will have to add your own logic for doing the transaction then the task enqueueing and handling the errors.
