### ISSUE TITLE
Inconsistent documentation on creating a task

### ISSUE THREAD

**Issue by jacobg** [googleapis/python-tasks#28]
This client library's documentation for the `create_task` function includes optional parameters for `retry`, `timeout`, and `metadata`, as shown here:
https://googleapis.dev/python/cloudtasks/latest/gapic/v2/api.html?highlight=create_task#google.cloud.tasks_v2.CloudTasksClient.create_task

However, the Cloud Tasks REST API does not include such parameters, as shown here:
https://cloud.google.com/tasks/docs/reference/rest/v2/projects.locations.queues.tasks/create

In fact, on another REST API web page, it explicitly states:

> RetryConfig
> Settings that determine the retry behavior.
> 
> For tasks created using Cloud Tasks: the queue-level retry settings apply to all tasks in the queue that were created using Cloud Tasks. Retry settings cannot be set on individual tasks.
>
> For tasks created using the App Engine SDK: the queue-level retry settings apply to all tasks in the queue which do not have retry settings explicitly set on the task and were created by the App Engine SDK. See App Engine documentation.

https://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Tasks.V2/api/Google.Cloud.Tasks.V2.Queue.html#Google_Cloud_Tasks_V2_Queue_RetryConfig

It's not clear what to rely on here. Can you please clarify? Thanks.

**Comment by davidwtbuxton** [comment]
Hi Jacob,

From reading [the linked docs][1], the retry, timeout and metadata arguments are used for controlling the gRPC request itself, and are common to all gRPC requests (not specific to the tasks API).

The parameters used by the tasks API itself should be supplied as [fields in the task argument][2] to the create_task request.

David



[1]: https://googleapis.dev/python/cloudtasks/latest/gapic/v2/api.html?highlight=create_task#google.cloud.tasks_v2.CloudTasksClient.create_task
[2]: https://googleapis.dev/python/cloudtasks/latest/gapic/v2/types.html#google.cloud.tasks_v2.types.Task

**Comment by jacobg** [comment]
Ah thanks for clarifying @davidwtbuxton. I didn't notice that.

So it sounds like the old App Engine Task API retry_options is unfortunately no longer an option. That's too bad, since it's nice for the caller to tweak retry options on an individual basis. In the new API, each queue will have its retry strategy configured up front.

**Comment by jacobg** [comment]
Closing this issue.

**Comment by davidwtbuxton** [comment]
Personally I reckon allowing specific tasks on a queue to have custom retry settings will lead to confusion.

Either way, please note that there are some differences depending on [how a queue is created on App Engine][1].

[1]: https://cloud.google.com/tasks/docs/queue-yaml
