### ISSUE TITLE
Clear example of usage for `create_task`

### ISSUE THREAD

**Issue by MeLight** [googleapis/python-tasks#33]
Here's the documentation example for creating a task:
![image](https://user-images.githubusercontent.com/704484/88285893-8a272b80-ccf8-11ea-8094-3e67c42739d1.png)

Is it just me, or is it missing the important parts?
Specifically, I would like to know how to provide the URL of the handler I want the task to call, and second, I'd like to send a payload.
I'm going to research the docs now. Thanks

**Comment by grant** [comment]
Hi @MeLight, can you link the example you see?
It looks like this is generated code.

Are you looking for something like this?
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/tasks/create_http_task.py

**Comment by MeLight** [comment]
Nope, this is part of what seems to be the official docs. 
You can find it here: https://googleapis.dev/python/cloudtasks/latest/gapic/v2/api.html

And this is how I found that specific page:
go to repo homepage: https://github.com/googleapis/python-tasks
scroll down, and click [Client Library Documentation](https://googleapis.dev/python/cloudtasks/latest/index.html)
when in the homepage of the docs, click on the left, topmost [Client for Cloud Tasks API](https://googleapis.dev/python/cloudtasks/latest/gapic/v2/api.html#)

**Comment by ShahzadUmair** [comment]
@MeLight are you looking for https://googleapis.dev/python/cloudtasks/latest/gapic/v2/types.html#google.cloud.tasks_v2.types.Task?

Why do you expect the docs explaining `create_task` to explain `task` too? 🤔

**Comment by averikitsch** [comment]
@grant linked the samples repo where you can find full samples. Here is the official doc that will give more explanation to the sample: https://cloud.google.com/tasks/docs/creating-appengine-tasks#python.
The docs show that task is type `(Union[dict, Task])` and @ShahzadUmair has linked that Task definition.
