### ISSUE TITLE
Documentation on scheduling a app_engine_http_request seems incorrect

### ISSUE THREAD

**Issue by Nathanmalnoury** [googleapis/python-tasks#62]
Hi, 

I'm having an issue creating scheduled Cloud Tasks, using python 2. 7 : they won't work throwing a TypeError.
It's probably worth noting that as long as I dont use the `in_seconds` every thing work as expected.

Am I missing something ?

Thanks

#### Environment details

  - OS type and version: Linux / Ubuntu 20.10
  - Python version: 2.7
  - pip version: 20.3.3
  - `google-cloud-tasks` version: 1.5.0

#### Steps to reproduce

  1. Follow the code sample to [create a task](https://cloud.google.com/tasks/docs/samples/cloud-tasks-appengine-create-task) using an `app_engine_http_request` 
  2. Create a task using ` in_seconds`
   

#### Code example
-> https://cloud.google.com/tasks/docs/samples/cloud-tasks-appengine-create-task

I also tried different combinations for 'schedule_time' :
```python
task['schedule_time'] = date.isoformat('T')
task['schedule_time'] = ' 2021-01-07T10:20:50.52Z'  # future date, inferior to 30 days from now 

# Using future.backports.datetime
task['schedule_time'] = date.isoformat('T')
```

Nothing worked.

#### Stack trace
```
ERROR    2020-12-31 11:28:56,442 handlers.py:120] Traceback (most recent call last):
  File "/home/nathan/myproject/lib/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nathan/myproject/lib/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nathan/myproject/app/main/admin/migrations.py", line 34, in reindex_enterprise
    migrate_by_pieces(400, _in_seconds=5 * 60)
  File "/home/nathan/myproject/app/deferredv3.py", line 70, in wrapper_defer
    path=u'/function-handler/{}'.format(f.__name__))
  File "/home/nathan/myproject/app/deferredv3.py", line 113, in send_deferred_task
    task = client.create_task(parent=parent, task=task)
  File "/home/nathan/myproject/lib/google/cloud/tasks_v2/gapic/cloud_tasks_client.py", line 1492, in create_task
    parent=parent, task=task, response_view=response_view
TypeError: Parameter to MergeFrom() must be instance of same class: expected google.protobuf.Timestamp got datetime.datetime.
```

**Comment by Nathanmalnoury** [comment]
I just tried the same thing using python3.8 and google-cloud-tasks 2.0.0 (using the code example from the documentation), and obtained the same error.

**Comment by Nathanmalnoury** [comment]
It would seem that this is an issue of documentation, rather than an issue of the API in it-self. 
By modifying the snippet found in the doc by the following, I was able to schedule a task as expected: 
```python
"""Create a task for a given queue with an arbitrary payload."""

from google.cloud import tasks_v2
from time import time
from google.cloud.tasks_v2.proto.target_pb2 import HttpMethod

# Create a client.
client = tasks_v2.CloudTasksClient()

# TODO(developer): Uncomment these lines and replace with your values.
# project = 'my-project-id'
# queue = 'my-appengine-queue'
# location = 'us-central1'
# payload = 'hello'

# Construct the fully qualified queue name.
parent = client.queue_path(project, location, queue)

# Construct the request body.
task = {
        'app_engine_http_request': {  # Specify the type of request.
            'http_method': HttpMethod.POST,
            'relative_uri': '/example_task_handler'
        }
}
if payload is not None:
    # The API expects a payload of type bytes.
    converted_payload = payload.encode()

    # Add the payload to the request.
    task['app_engine_http_request']['body'] = converted_payload

if in_seconds is not None:
    # Time of requested execution, in seconds
    seconds = seconds=int(time() + in_seconds)

    # Add the timestamp to the tasks.
    task['schedule_time'] = tasks_v2.types.Timestamp(seconds=seconds)

# Use the client to build and send the task.
response = client.create_task(parent=parent, task=task)

print('Created task {}'.format(response.name))
return response
```

**Comment by averikitsch** [comment]
Please update to the newest library version for the sample to work as is: [2.1.0](https://github.com/googleapis/python-tasks/blob/master/samples/snippets/requirements.txt)

**Comment by averikitsch** [comment]
Please re-open if you are still experiencing this issue.

**Comment by pduggi-cf** [comment]
Hi, 

I am seeing this issue in version 2.3.0 

I am running the below

`timestamp = datetime.datetime.utcnow() + datetime.timedelta(seconds=30)

task['schedule_time'] = timestamp

client.create_task(parent = parent, task=task)`

I get `Parameter to MergeFrom() must be instance of same class: expected google.protobuf.Timestamp got datetime.datetime.`

**Comment by averikitsch** [comment]
Hi @pduggi-cf , please see the sample for converting datetime to Timestamp:
https://github.com/googleapis/python-tasks/blob/2243d84b3693974648b8c8f122b897b9f8ca437c/samples/snippets/create_http_task.py#L68-L72

**Comment by pduggi-cf** [comment]
The documentation at https://cloud.google.com/tasks/docs/creating-appengine-tasks seems to be the problem 

Thanks for pointing me in the right direction ☺️
