### ISSUE TITLE
Cloud Tasks version 2 documentation

### ISSUE THREAD

**Issue by natasha-aleksandrova** [googleapis/python-tasks#82]
Is there a documentation with full examples on how to create a task in the new version?

We've updated the library (2.2.0) and our code no longer works, I haven't found a full example on how to create a task and am stuck on setting headers.

Supposed to use `types.HttpRequest.HeadersEntry` but how do I actually set the headers values?

I've tried `HeadersEntry(content_type='application/json')` or `HeadersEntry(**{"Content-Type": "application/json"})` and neither work.

**Comment by mdgregor** [comment]
My team is also having this issue and would love some concrete examples.

**Comment by averikitsch** [comment]
Check out this [sample](https://github.com/googleapis/python-tasks/blob/master/samples/snippets/create_http_task.py) which adds a content-type to the request: 
https://github.com/googleapis/python-tasks/blob/6f25ccab47d8a0efa4b330a9eb0c421b7004815e/samples/snippets/create_http_task.py#L47-L64

Samples can be found [here](https://github.com/googleapis/python-tasks/tree/master/samples/snippets) with a complete list found [here](https://cloud.google.com/tasks/docs/samples).

Please let me know if you have further questions.

**Comment by natasha-aleksandrova** [comment]
Isn't that the old way to create the task?


```    response = get_cloud_tasks_client().create_task(
        parent=queue,
        task=types.Task(http_request=types.HttpRequest(
            url=f"https://{SERVICE_DOMAIN}" + api,
            http_method=types.HttpMethod.POST,
            headers=[types.HttpRequest.HeadersEntry(mapping={"Content-Type": "foo"})],
            body=dumps(body),
            oidc_token=types.OidcToken(service_account_email=SA_OIDC_EMAIL)
        )),
    )
```

2.2.0 requires objects in order to create a task.

**Comment by averikitsch** [comment]
@busunkim96 Can you advise and are new samples going to be added?

**Comment by busunkim96** [comment]
There are no breaking changes between 2.0.0 and 2.2.0

The sample that @averikitsch linked to was tested with 2.2.0 and merged after those tests passed. https://github.com/googleapis/python-tasks/pull/71. I checked the nightlies and those are also passing.

What sort of error/warning are you seeing? @natasha-aleksandrova

**Comment by natasha-aleksandrova** [comment]
The library was updated from 1.5.0 to 2.2.0. The signature of create_task is different between the two.

The question was about setting Headers via `types.HttpRequest.HeadersEntry` object as per your documentation.

The code sample linked uses `request` param and passes in a dict -- the docs say that `request` param is a `CreateTaskRequest` object. 


in 1.5.0 we created a task like this:
```
task = {
        "http_request": {
            "headers": {"Content-type": "application/json"},
            "http_method": "POST",
            "url": f"https://{SERVICE_DOMAIN}" + api,
            "body": dumps(body),
            "oidc_token": {
                "service_account_email": SA_OIDC_EMAIL
            }
        }
    }
create_task(queue, task)
```

are you saying we can still pass in a dict in 2.2.0?

**Comment by busunkim96** [comment]
Ah, I see you're upgrading from 1.5.0. https://github.com/googleapis/python-tasks/blob/master/UPGRADING.md explains the major differences between 1.x and 2.x (there _are_ breaking changes). The samples are all up to date with the latest release, so referencing them should be helpful for migrating.


The docs unfortunately have incorrect type annotations (tracked in https://github.com/googleapis/gapic-generator-python/issues/715), but yes you can pass a `CreateTaskRequest` _or_ a `dict` with keys that match the fields. You can mix as well.

```py
from google.cloud import tasks_v2

SERVICE_DOMAIN = ""
SA_OIDC_EMAIL = ""
api = ""
body = b""
parent = ""

# Your example
task_w_dicts = {
    "http_request": {
        "headers": {"Content-type": "application/json"},
        "http_method": "POST",
        "url": f"https://{SERVICE_DOMAIN}" + api,
        "body": body,
        "oidc_token": {"service_account_email": SA_OIDC_EMAIL},
    }
}

# Same task using types instead of dict
task_w_classes = tasks_v2.Task(
    http_request=tasks_v2.HttpRequest(
        headers={"Content-type": "application/json"},
        http_method=tasks_v2.HttpMethod.POST,
        url=f"https://{SERVICE_DOMAIN}" + api,
        body=body,
        oidc_token=tasks_v2.OidcToken(service_account_email=SA_OIDC_EMAIL),
    )
)

# Mixing in dicts is okay too
task_w_mix = tasks_v2.Task(
    http_request=tasks_v2.HttpRequest(
        headers={"Content-type": "application/json"},
        http_method=tasks_v2.HttpMethod.POST,
        url=f"https://{SERVICE_DOMAIN}" + api,
        body=body,
        oidc_token={"service_account_email": SA_OIDC_EMAIL},
    )
)

assert tasks_v2.Task(task_w_dicts) == task_w_classes
assert task_w_classes == task_w_mix
```


There are also multiple ways to call the method:

```py
# Create request object
request = tasks_v2.CreateTaskRequest(parent=parent, task=task)
client.create_task(request)

# Create request dict
request = {"parent": parent, "task": task}
client.create_task(request)

# Pass `parent` and `task` as kwargs to method
client.create_task(parent=parent, task=task)
```

**Comment by natasha-aleksandrova** [comment]
@busunkim96 thank you this helps!
